export enum TestStatus {
  TEST_CREATED = "TEST_CREATED",
  SPEAKING_TEST_CREATED = "SPEAKING_TEST_CREATED",
  SPEAKING_TEST_PART_2_STARTED = "SPEAKING_TEST_PART_2_STARTED",
  SPEAKING_TEST_PART_2_COMPLETED = "SPEAKING_TEST_PART_2_COMPLETED",
  SPEAKING_TEST_PART_2_EVALUATED = "SPEAKING_TEST_PART_2_EVALUATED",
  SPEAKING_TEST_PART_2_FAILED = "SPEAKING_TEST_PART_2_FAILED",
  SPEAKING_TEST_PART_3_STARTED = "SPEAKING_TEST_PART_3_STARTED",
  SPEAKING_TEST_PART_3_COMPLETED = "SPEAKING_TEST_PART_3_COMPLETED",
  SPEAKING_TEST_PART_3_EVALUATED = "SPEAKING_TEST_PART_3_EVALUATED",
  SPEAKING_TEST_PART_3_FAILED = "SPEAKING_TEST_PART_3_FAILED",

  WRITING_TEST_CREATED = "WRITING_TEST_CREATED",
  WRITING_TEST_STAGES_GENERATED = "WRITING_TEST_STAGES_GENERATED",

  READING_TEST_CREATED = "READING_TEST_CREATED",
  READING_TEST_STAGE_ONE_GENERATED = "READING_TEST_STAGE_ONE_GENERATED",
  READING_TEST_STAGE_TWO_GENERATED = "READING_TEST_STAGE_TWO_GENERATED",
  READING_TEST_STAGE_THREE_GENERATED = "READING_TEST_STAGE_THREE_GENERATED",

  LISTENING_TEST_CREATED = "LISTENING_TEST_CREATED",
  LISTENING_TEST_STAGE_ONE_TEXT_GENERATED = "LISTENING_TEST_STAGE_ONE_TEXT_GENERATED",
  LISTENING_TEST_STAGE_TWO_TEXT_GENERATED = "LISTENING_TEST_STAGE_TWO_TEXT_GENERATED",
  LISTENING_TEST_STAGE_THREE_TEXT_GENERATED = "LISTENING_TEST_STAGE_THREE_TEXT_GENERATED",
  LISTENING_TEST_STAGE_ONE_QUESTIONS_GENERATED = "LISTENING_TEST_STAGE_ONE_QUESTIONS_GENERATED",
  LISTENING_TEST_STAGE_TWO_QUESTIONS_GENERATED = "LISTENING_TEST_STAGE_TWO_QUESTIONS_GENERATED",
  LISTENING_TEST_STAGE_THREE_QUESTIONS_GENERATED = "LISTENING_TEST_STAGE_THREE_QUESTIONS_GENERATED",
  LISTENING_TEST_STAGE_FOUR_QUESTIONS_GENERATED = "LISTENING_TEST_STAGE_FOUR_QUESTIONS_GENERATED",
  LISTENING_TEST_STAGE_ONE_AUDIO_GENERATED = "LISTENING_TEST_STAGE_ONE_AUDIO_GENERATED",
  LISTENING_TEST_STAGE_TWO_AUDIO_GENERATED = "LISTENING_TEST_STAGE_TWO_AUDIO_GENERATED",
  LISTENING_TEST_STAGE_THREE_AUDIO_GENERATED = "LISTENING_TEST_STAGE_THREE_AUDIO_GENERATED",
  LISTENING_TEST_STAGE_FOUR_AUDIO_GENERATED = "LISTENING_TEST_STAGE_FOUR_AUDIO_GENERATED",
}

// export enum PracticeSpeakingTestStatus {
//   CREATED = "CREATED",
//   PART_2_STARTED = "PART_2_STARTED",
//   PART_2_COMPLETED = "PART_2_COMPLETED",
//   PART_2_EVALUATED = "PART_2_EVALUATED",
//   PART_2_FAILED = "PART_2_FAILED",
//   PART_3_STARTED = "PART_3_STARTED",
//   PART_3_COMPLETED = "PART_3_COMPLETED",
//   PART_3_EVALUATED = "PART_3_EVALUATED",
//   PART_3_FAILED = "PART_3_FAILED",
// }

export enum TestStageStatus {
  CREATED = "CREATED",
  QUESTIONS_GENERATED = "QUESTIONS_GENERATED",
  STARTED = "STARTED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  EVALUATED = "EVALUATED",
}

export enum QuestionStatus {
  CREATED = "CREATED",
  STARTED = "STARTED",
  ANSWER_SUBMITTED = "ANSWER_SUBMITTED",
  FAILED = "FAILED",
  EVALUATED = "EVALUATED",
}

export enum TestOperations {
  EVALUATE = "evaluate",
}

export enum SpeakingTestOperation {
  START = "start",
  STOP = "stop",
}

export enum TestQuestionTypes {
  MULTIPLE_CHOICE = "Multiple Choice",
  MATCHING_HEADINGS = "Matching Headings",
  MATCHING_INFORMATION = "Matching Information",
  MATCHING_FEATURES = "Matching Features",
  SENETENCE_COMPLETION = "Sentence Completion",
  TRUE_FALSE = "True False",
}

export enum ListeningTestTextTypes {
  CONVERSATION = "conversation",
  MONOLOUGE = "monologue",
  DIALOG = "dialog",
}

export enum CognitoChallanges {
  NEW_PASSWORD_REQUIRED = "NEW_PASSWORD_REQUIRED",
}

export enum SigninResponseStatus {
  AUTHENTICATED = "AUTHENTICATED",
  NEW_PASSWORD_REQUIRED = "NEW_PASSWORD_REQUIRED",
}

export enum UserTypes {
  STUDENT = "student",
  ADMIN = "admin",
  INSTRUCTOR = "instructor",
}
