export enum TestStatus {
  TEST_CREATED = "TEST_CREATED",
  SPEAKING_TEST_CREATED = "SPEAKING_TEST_CREATED",
  SPEAKING_TEST_PART_2_STARTED = "SPEAKING_TEST_PART_2_STARTED",
  SPEAKING_TEST_PART_2_COMPLETED = "SPEAKING_TEST_PART_2_COMPLETED",
  SPEAKING_TEST_PART_2_EVALUATED = "SPEAKING_TEST_PART_2_EVALUATED",
  SPEAKING_TEST_PART_2_FAILED = "SPEAKING_TEST_PART_2_FAILED",
  SPEAKING_TEST_PART_3_STARTED = "SPEAKING_TEST_PART_3_STARTED",
  SPEAKING_TEST_PART_3_COMPLETED = "SPEAKING_TEST_PART_3_COMPLETED",
  SPEAKING_TEST_PART_3_EVALUATED = "SPEAKING_TEST_PART_3_EVALUATED",
  SPEAKING_TEST_PART_3_FAILED = "SPEAKING_TEST_PART_3_FAILED",

  WRITING_TEST_CREATED = "WRITING_TEST_CREATED",
  WRITING_TEST_STAGES_GENERATED = "WRITING_TEST_CREATED",
}

// export enum PracticeSpeakingTestStatus {
//   CREATED = "CREATED",
//   PART_2_STARTED = "PART_2_STARTED",
//   PART_2_COMPLETED = "PART_2_COMPLETED",
//   PART_2_EVALUATED = "PART_2_EVALUATED",
//   PART_2_FAILED = "PART_2_FAILED",
//   PART_3_STARTED = "PART_3_STARTED",
//   PART_3_COMPLETED = "PART_3_COMPLETED",
//   PART_3_EVALUATED = "PART_3_EVALUATED",
//   PART_3_FAILED = "PART_3_FAILED",
// }

export enum TestStageStatus {
  CREATED = "CREATED",
  STARTED = "STARTED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  EVALUATED = "EVALUATED",
}

export enum QuestionStatus {
  CREATED = "CREATED",
  STARTED = "STARTED",
  ANSWER_SUBMITTED = "ANSWER_SUBMITTED",
  FAILED = "FAILED",
  EVALUATED = "EVALUATED",
}

export enum WritingTestOperation {
  EVALUATE = "evaluate",
}
