export enum TestStatus {
  TEST_CREATED = "TEST_CREATED",
  SPEAKING_TEST_CREATED = "SPEAKING_TEST_CREATED",
  SPEAKING_TEST_PART_1_STARTED = "SPEAKING_TEST_PART_1_STARTED",
  SPEAKING_TEST_PART_1_COMPLETED = "SPEAKING_TEST_PART_1_COMPLETED",
  SPEAKING_TEST_PART_1_EVALUATED = "SPEAKING_TEST_PART_1_EVALUATED",
  SPEAKING_TEST_PART_1_FAILED = "SPEAKING_TEST_PART_1_FAILED",
  SPEAKING_TEST_PART_2_STARTED = "SPEAKING_TEST_PART_1_STARTED",
  SPEAKING_TEST_PART_2_COMPLETED = "SPEAKING_TEST_PART_1_COMPLETED",
  SPEAKING_TEST_PART_2_EVALUATED = "SPEAKING_TEST_PART_1_EVALUATED",
  SPEAKING_TEST_PART_2_FAILED = "SPEAKING_TEST_PART_1_FAILED",
}

export enum TestPartStatus {
  CREATED = "CREATED",
  STARTED = "STARTED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  EVALUATED = "EVALUATED",
}

export enum QuestionStatus {
  CREATED = "CREATED",
  STARTED = "STARTED",
  ANSWER_SUBMITTED = "ANSWER_SUBMITTED",
  FAILED = "FAILED",
  EVALUATED = "EVALUATED",
}
