const GptPrompts = {
  StageTwoSpeakingQuestionGenerationPrompt: (context: string) => {
    return `You are a english language expert who make IELTS speaking exam questions in British council , Generate a Task card for IELTS speaking test part 2 which is more similler to real exam in the context of ${context}. give me the result without any additional headings like "Of course! Here's a task card for Part 2 of the IELTS speaking test"`;
  },
  StageThreeSpeakingQuestionGenerationPrompt: (previousQuestion: string) => {
    return `You are a English language expert who conduct IELTS speaking exam with student in British council , Now student have given the speach on follwing questions and points. 

      "${previousQuestion}"

      Generate some maximum five questions for speaking test part 3. give me the result without any additional headings and in bullet points only
    `;
  },
  StageOneWritingTestQuestionGenerationPrompt: (context: string) => {
    return `You are an English language expert who creates IELTS General Training writing exam questions at the British Council. Generate a Task for IELTS General Training Writing Test Part 1 in the context of '${context}' which is more similar to a real exam. Provide the result without any additional headings, just the question and points are sufficient.`;
  },

  StageTwoWritingTestQuestionGenerationPrompt: (context: string) => {
    return `You are an English language expert who creates IELTS General Training writing exam task 2 questions. Generate a Essay Task for IELTS General Training Writing Test task 2  in the context of '${context}' which is more similar to a real exam. Provide the question without any additional headings`;
  },

  StageOneReadingTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training reading exam task 1 questions. Generate a real scenario text for task 1 with real-world information for the IELTS General Training Reading Test by applying the following constraints
      1 - Give me the text only, no questions
      2- The context of the text should be '${context}'
      3- You must generate the text by applying real values for all placeholders like time venue, location, date, name, email, titles or personal info placeholders
      4- Text must not contain any placeholders
      5- The word count of the text should be more than 200
      6- Give a suitable topic for the text as well
    `;
  },

  StageTwoReadingTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training reading exam task 2. Generate a real scenario text for task 2 with real-world information for the IELTS General Training Reading Test by applying the following constraints
      1 - Give me the text only, no questions
      2 - The context of the text should be '${context}'
      3 - Text must not contain any placeholders
      4 - The word count of the text should be more than 300
      5 - Give a suitable topic for the text as well
    `;
  },

  StageThreeReadingTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training reading exam task 3. Generate a real scenario text for task 3 with real-world information for the IELTS General Training Reading Test by applying the following constraints
      1 - Give me the text only, no questions
      2 - The context of the text should be '${context}'
      3 - Text must not contain any placeholders
      4 - The word count of the text should be more than 350
      5 - Give a suitable topic for the text as well
    `;
  },

  ReadingTestQuestionGenerationSystemPrompt: (task: number) => {
    return `You are an English language expert who creates IELTS General Training reading exam task ${task} questions. Based on a given reading exam text which was 
    generated by you, questions must be generated as user specified`;
  },

  ReadingTestMcqQuestionGenerationPrompt: () => {
    return `You must generate a One Multiple Choice question similer to real IELTS general test reading exam based on above text. question should have four options. 
    Question must be a different question than the ones generated previosuly by you. Don't include any answers to questions. Don't add prfix 'Question'. List of 
    options should be seperated to immediate next line by exactly one new line charactor`;
  },

  ReadingTestSentenceCompletionQuestionGenerationPrompt: () => {
    return `You must generate a One Sentence Completion question similer to real IELTS general test reading exam based on above text. Question must be a different 
    question than the ones generated previosuly by you. Don't include any answers to questions. Don't add prfix 'Question'. Question must contain only one space to complete`;
  },

  ReadingTestQuestionEvaluationSystemPrompt: () => {
    return `You are an English language expert who evaluate answers for the IELTS General Training reading exam task 1 questions. Based on a given reading exam text which was generated by you, you have to evaluate the answer for questions which will be given by user. You will be always provide folowing after evaluation
            - In a new line, Provide wheather answer is correct or wrong using the word 'Correct' or 'Wrong'. Don't include any other prefixes or suffixes
            - In a new line, Provide the correct answer regardless of the answer is correct or wrong. Don't include any other prefixes or suffixes`;
  },

  ReadingTestQuestionEvaluationUserPrompt: (question: string, answer: string) => {
    return `Question: '${question}'
            Answer: '${answer}.'`;
  },

  // StageOneReadingTestQuestionGenerationPrompt: (text: string, categories: Array<string>) => {
  //   return `
  //         You are an English language expert who creates IELTS General Training reading exam task 1 questions. Generate 13 questions based on the text provided in following for IELTS General Training reading exam task 1.
  //         The questions should be from categories of [Multiple Choice and Sentence Completion]
  //         You must give the response in following way

  //         1- Questions must be similer to real exam
  //         2- Questions must be given in the order of categories given above
  //         3- Each category should be seperated by the token 'category' (don't add real category name here)
  //         4- Each question in each category should be seperated by the token 'question'

  //         text:

  //         ${text}
  //         `;
  // },
  WritingTestQuestionEvaluationSystemPrompt: (writingTestPart: number) => {
    return `You are an expert English teacher who excels at training candidates in IELTS. 

    You will help grade the IELTS General Training Writing Test Part ${writingTestPart} by the user. You will always provide the following:
    - The overall score
    - The breakdown of each band /criteria
    - Areas to improve with examples`;
  },

  WritingTestQuestionEvaluationUserPrompt: (question: string, answer: string) => {
    return `Question: '${question}'
            Answer: '${answer}.'`;
  },
};

export default GptPrompts;
