const GptPrompts = {
  StageTwoSpeakingQuestionGenerationPrompt: (context: string) => {
    return `You are a english language expert who make IELTS speaking exam questions in British council , Generate a Task card for IELTS speaking test part 2 which is more similler to real exam in the context of ${context}. give me the result without any additional headings like "Of course! Here's a task card for Part 2 of the IELTS speaking test"`;
  },
  StageThreeSpeakingQuestionGenerationPrompt: (previousQuestion: string) => {
    return `You are a English language expert who conduct IELTS speaking exam with student in British council , Now student have given the speach on follwing questions and points. 

      "${previousQuestion}"

      Generate some maximum five questions for speaking test part 3. give me the result without any additional headings and in bullet points only
    `;
  },
  StageOneWritingTestQuestionGenerationPrompt: (context: string) => {
    return `You are an English language expert who creates IELTS General Training writing exam questions at the British Council. Generate a Task for IELTS General Training Writing Test Part 1 in the context of '${context}' which is more similar to a real exam. Provide the result without any additional headings, just the question and points are sufficient.`;
  },

  StageTwoWritingTestQuestionGenerationPrompt: (context: string) => {
    return `You are an English language expert who creates IELTS General Training writing exam task 2 questions. Generate a Essay Task for IELTS General Training Writing Test task 2  in the context of '${context}' which is more similar to a real exam. Provide the question without any additional headings`;
  },

  /*------ Reading Test Prompts ----------------------------------------------------------------------------------------------------------------------------------- */

  StageOneReadingTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training reading exam task 1 questions. Generate a real scenario text for task 1 with real-world information for the IELTS General Training Reading Test by applying the following constraints
      1 - Give me the text only, no questions
      2- The context of the text should be '${context}'
      3- You must generate the text by applying real values for all placeholders like time venue, location, date, name, email, titles or personal info placeholders
      4- Text must not contain any placeholders
      5- The word count of the text should be more than 200
      6- Give a suitable topic for the text as well
    `;
  },

  StageTwoReadingTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training reading exam task 2. Generate a real scenario text for task 2 with real-world information for the IELTS General Training Reading Test by applying the following constraints
      1 - Give me the text only, no questions
      2 - The context of the text should be '${context}'
      3 - Text must not contain any placeholders
      4 - The word count of the text should be more than 300
      5 - Give a suitable topic for the text as well
    `;
  },

  StageThreeReadingTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training reading exam task 3. Generate a real scenario text for task 3 with real-world information for the IELTS General Training Reading Test by applying the following constraints
      1 - Give me the text only, no questions
      2 - The context of the text should be '${context}'
      3 - Text must not contain any placeholders
      4 - The word count of the text should be more than 350
      5 - Give a suitable topic for the text as well
    `;
  },

  ReadingTestQuestionGenerationSystemPrompt: (task: number) => {
    return `You are an English language expert who creates IELTS General Training reading exam task ${task} questions. Based on a given reading exam text which was 
    generated by you, questions must be generated as user specified`;
  },

  ReadingTestMcqQuestionGenerationPrompt: () => {
    return `You must generate a One Multiple Choice question similer to real IELTS general test reading exam based on above text. question should have four options. 
    Question must be a different question than the ones generated previosuly by you. Don't include any answers to questions. Don't add prfix 'Question'. List of 
    options should be seperated to immediate next line by exactly one new line charactor`;
  },

  ReadingTestSentenceCompletionQuestionGenerationPrompt: () => {
    return `You must generate a One Sentence Completion question similer to real IELTS general test reading exam based on above text. Question must be a different 
    question than the ones generated previosuly by you. Don't include any answers to questions. Don't add prfix 'Question'. Question must contain only one space to complete`;
  },

  ReadingTestQuestionEvaluationSystemPrompt: () => {
    return `You are an English language expert who evaluate answers for the IELTS General Training reading exam task 1 questions. Based on a given reading exam text which was generated by you, you have to evaluate the answer for questions which will be given by user. You will be always provide folowing after evaluation
            - In a new line, Provide wheather answer is correct or wrong using the word 'Correct' or 'Wrong'. Don't include any other prefixes or suffixes
            - In a new line, Provide the correct answer regardless of the answer is correct or wrong. Don't include any other prefixes or suffixes`;
  },

  ReadingTestQuestionEvaluationUserPrompt: (question: string, answer: string) => {
    return `Question: '${question}'
            Answer: '${answer}.'`;
  },
  /*--------------------------------------------------------------------------------------------------------------------------------------------------------------- */

  /*------ Listening Test Prompts --------------------------------------------------------------------------------------------------------------------------------- */
  StageOneListeningTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training listening exam task 1 questions. Generate a real conversation text for task 1 between two persons with real-world information for the IELTS General Training Listening Test by applying the following constraints
      1 - conversation must be at least 400 words long
      2 - Indicate Each person in conversation only with a number assigned to him or her
      3 - The context for the conversation should be '${context}'
      4 - You should give the conversation only, not any extra text, prefixes or suffixes at the end and start of the conversation
      5 - each person line should beging in a new line and must be in format of - 'personNumber: personText'
    `;
  },

  StageTwoListeningTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training listening exam task 2. Generate a real scenario text with real-world information for the IELTS General Training listening Test task 2 by applying the following constraints
      1 - Give me the text only, no questions
      2 - The context of the text should be '${context}'
      3 - Text must not contain any placeholders
      4 - The word count of the text should be more than 400
    `;
  },

  StageThreeListeningTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training listening exam task 3. Generate a real dialog text with real-world information for the IELTS General Training listening Test task 3 by applying the following constraints
      1 - The text must be three person dialog 
      1 - The tone should be conversational tone
      2 - The word count of the text should be more than 400
      3 - The context of the text should be '${context}'
      4 - Text must not contain any placeholders
      5 - You should give the dialog only, not any extra text, prefixes or suffixes at the end and start of the dialog
      6 - each person line should beging in a new line and must be in format of - 'personNumber: personText'
      7 - Each person should talk consecutively, which means person1 -> person2 -> person3 and then again person1-> person2 -> person3, then continue the patteren
      8 - use real names for person names when others call them
    `;
  },

  StageFourListeningTestTextGenerationPrompt: (context: string) => {
    return `
    You are an English language expert who creates IELTS General Training listening exam task 4. Generate a real scenario text with real-world information for the IELTS General Training listening Test task 4 by applying the following constraints
      1 - Give me the text only, no questions
      2 - The context of the text should be '${context}'
      3 - Text must not contain any placeholders
      4 - The word count of the text should be less than 400
    `;
  },

  ListeningTestQuestionGenerationSystemPrompt: (task: number, textType: string) => {
    return `You are an English language expert who creates IELTS General Training listening exam task ${task} questions. Based on a given ${textType} which was 
    generated by you, questions must be generated as user specified`;
  },

  ListeningTestMcqQuestionGenerationPrompt: (textType: string) => {
    return `You must generate a One Multiple Choice question similer to real IELTS general test listening exam based on above ${textType}. question should have four options. 
    Question must be a different question than the ones generated previosuly by you. Don't include any answers to questions. Don't add prfix 'Question'. List of 
    options should be seperated to immediate next line by exactly one new line charactor`;
  },

  ListeningTestTrueFalseQuestionGenerationPrompt: (textType: string) => {
    return `You must generate a One 'True' 'False' 'Not Given' question similar to a real IELTS general test listening exam based on the above ${textType}. Only Question is needed.
    Don't add any prefixes. The question must be a different question than the ones generated previously by you. Don't include True / False / Not Given options`;
  },

  ListeningTestMCQQuestionEvaluationSystemPrompt: () => {
    return `You are an English language expert who evaluate answers for the IELTS General Training listening exam task questions. Based on a given text translation of listening exam audio which was generated by you, you have to evaluate the answer for a MCQ question with four options which will be given by user. You will be always provide folowing after evaluation
            - In a new line, Provide wheather answer is correct or wrong using the word 'Correct' or 'Wrong'. Don't include any other prefixes or suffixes
            - In a new line, Provide the correct answer with the option letter as well as the text line for that option regardless of the answer is correct or wrong. Don't include any other prefixes or suffixes`;
  },

  ListeningTestTrueFlaseQuestionEvaluationSystemPrompt: () => {
    return `You are an English language expert who evaluate answers for the IELTS General Training listening exam task questions. Based on a given text translation of listening exam audio which was generated by you, you have to evaluate the answer for a True False type question which will be given by user. You will be always provide folowing after evaluation
            - In a new line, Provide wheather answer is correct or wrong using the word 'Correct' or 'Wrong'. Don't include any other prefixes or suffixes
            - In a new line, Provide the correct answer regardless of the answer is correct or wrong. Don't include any other prefixes or suffixes`;
  },

  ListeningTestQuestionEvaluationUserPrompt: (question: string, answer: string) => {
    return `Question: '${question}'
            Answer: '${answer}.'`;
  },

  /*--------------------------------------------------------------------------------------------------------------------------------------------------------------- */

  // StageOneReadingTestQuestionGenerationPrompt: (text: string, categories: Array<string>) => {
  //   return `
  //         You are an English language expert who creates IELTS General Training reading exam task 1 questions. Generate 13 questions based on the text provided in following for IELTS General Training reading exam task 1.
  //         The questions should be from categories of [Multiple Choice and Sentence Completion]
  //         You must give the response in following way

  //         1- Questions must be similer to real exam
  //         2- Questions must be given in the order of categories given above
  //         3- Each category should be seperated by the token 'category' (don't add real category name here)
  //         4- Each question in each category should be seperated by the token 'question'

  //         text:

  //         ${text}
  //         `;
  // },
  WritingTestQuestionEvaluationSystemPrompt: (writingTestPart: number) => {
    return `You are an expert English teacher who excels at training candidates in IELTS. 

    You will help grade the IELTS General Training Writing Test Part ${writingTestPart} by the user. You will always provide the following:
    - The overall score
    - The breakdown of each band /criteria
    - Areas to improve with examples`;
  },

  WritingTestQuestionEvaluationUserPrompt: (question: string, answer: string) => {
    return `Question: '${question}'
            Answer: '${answer}.'`;
  },
};

export default GptPrompts;
