openapi: 3.0.3
info:
  title: ELanguageCenter IELTS B2B API
  description: This is the API definition for ELanguageCenter IELTS B2B(Business to Business) API
  termsOfService: http://swagger.io/terms/
  contact:
    email: elanguagecenter23@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /healthcheck:
    get:
      operationId: testHealth
      tags:
        - Health
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthResponse'
        '400':
          description: Invalid request in the payload
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInvalidErrorResponse'
        '401':
          description: User is unauthorized
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        '500':
          description: Internal server error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  /ielts/test:
    post:
      summary: Create new test
      description: Create a new IELTS test for a user
      operationId: createNewTest
      tags:
        - Test
      requestBody:
        description: New test request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/testRequest'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testResponse'
        '400':
          description: Invalid request in the payload
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInvalidErrorResponse'
        '401':
          description: User is unauthorized
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        '500':
          description: Internal server error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  
  /ielts/test/{testId}/speaking:
    post:
      summary: Create new speaking test
      description: Create a new IELTS speaking test for a user
      operationId: createNewSpeakingTest
      tags:
        - Speaking
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: string
      requestBody:
        description: New speaking test request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/speakingTestRequest'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speakingTestResponse'
        '400':
          description: Invalid request in the payload
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInvalidErrorResponse'
        '401':
          description: User is unauthorized
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        '500':
          description: Internal server error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  
  /ielts/test/{testId}/speaking/stages/{stgId}:
    post:
      summary: Create new speaking test stage
      description: Create a new stage in IELTS speaking test for a user
      operationId: createNewSpeakingTestStage
      tags:
        - Speaking
      parameters:
        - in: path
          name: stgId
          required: true
          schema:
            type: string
        - in: path
          name: testId
          required: true
          schema:
            type: string
      requestBody:
        description: New speaking test stage request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/speakingTestStageRequest'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speakingTestStageResponse'
        '400':
          description: Invalid request in the payload
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInvalidErrorResponse'
        '401':
          description: User is unauthorized
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        '500':
          description: Internal server error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
                
  /ielts/test/{testId}/speaking/stages/{stgId}/question/{qid}:
    get:
      summary: get speaking test question
      description: get question in IELTS speaking test in particular stage for a user
      operationId: getSpeakingTestQuestion
      tags:
        - Speaking
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: string
        - in: path
          name: stgId
          required: true
          schema:
            type: string
        - in: path
          name: qid
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speakingTestQuestionGetResponse'
        '400':
          description: Invalid request in the payload
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInvalidErrorResponse'
        '401':
          description: User is unauthorized
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        '500':
          description: Internal server error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
    put:
      summary: update speaking test question
      description: update question in IELTS speaking test in particular stage for a user
      operationId: updateSpeakingTestQuestion
      tags:
        - Speaking
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: string
        - in: path
          name: stgId
          required: true
          schema:
            type: string
        - in: path
          name: qid
          required: true
          schema:
            type: string
      requestBody:
        description: update speaking question request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/speakingTestQuestionUpdateRequest'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speakingTestQuestionUpdateResponse'
        '400':
          description: Invalid request in the payload
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataInvalidErrorResponse'
        '401':
          description: User is unauthorized
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        '500':
          description: Internal server error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'

components:
  schemas:
    #Health type
    healthResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
  
    # Test data types
    testRequest:
      type: object
      properties:
        name:
          type: string
          example: Test1
    testResponse:
      type: object
      properties:
        id:
          type: string
          example: 19c4bcd9-9bc3-4d65-a853-0a6081baad0a
        name:
          type: string
          example: Test1
          
    # Speaking Test data types
    speakingTestRequest:
      type: object
      properties:
        name:
          type: string
          example: SpeakingTest1
    speakingTestResponse:
      type: object
      properties:
        id:
          type: string
          example: 19c4bcd9-9bc3-4d65-a853-0a6081baad0a
        name:
          type: string
          example: SpeakingTest1
          
    # Speaking Test Stage data types
    speakingTestStageRequest:
      type: object
      properties:
        name:
          type: string
          example: SpeakingTestStage1
    speakingTestStageResponse:
      properties:
        id:
          type: string
          example: 19c4bcd9-9bc3-4d65-a853-0a6081baad0a
        name:
          type: string
          example: SpeakingTestStage1
        generatedQuestionCount:
          type: number
          example: 3
    
    # Speaking test question data types
    speakingTestQuestionGetResponse:
      type: object
      properties:
        question:
          type: string
          example: SpeakingTestStageQuestion1
        evaluationCriteria:
          type: string
          example: evaluationCriteria
        evaluatedResult:
          type: string
          example: evaluatedResult
        status:
          type: string
          example: INPROGRESS
        timeInMills:
          type: number
          example: 56465465151
    speakingTestQuestionUpdateRequest:
      type: object
      properties:
        operation:
          type: string
          example: START
    speakingTestQuestionUpdateResponse:
      type: object
      properties:
        status:
          type: string
          example: SUCCESS
        uploadedUrl:
          type: string
          example: https://s3.amazonaws.com/bucket1/object1

    
    # Error data types
    DataInvalidErrorResponse:
      type: object
      properties:
        code:
          type: number
          example: 400
        message:
          type: string
          example: Invalid test name
    UnauthorizedErrorResponse:
      type: object
      properties:
        code:
          type: number
          example: 401
        message:
          type: string
          example: User is unauthorized or session is expired
    InternalErrorResponse:
      type: object
      properties:
        code:
          type: number
          example: 500
        message:
          type: string
          example: Database error

  securitySchemes:
    bearerAuth:  # Moved the section to align with components
      type: http
      scheme: bearer
